import Head from 'next/head'
import Image from 'next/image'
import Navbar from '../../components/Navbar'
import Footer from '../../components/Footer'

import { FaRocket } from 'react-icons/fa'

export default function Home() {
  return (
    <div>
      <Head>
        <title>MiniODY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='min-h-screen flex flex-col'>
        <Navbar />
        <main className="flex-1 mt-10 mx-auto sm:mt-12 md:mt-16 lg:mt-20 pb-48 xs:overflow-hidden md:overflow-visible">
          <h1 className="text-3xl mx-auto font-extrabold tracking-tight text-white sm:text-4xl pb-4 sm:pb-4">All Projects</h1>
          <p className="text-base text-gray-500 sm:text-lg mx-auto md:text-xl lg:mx-0 pb-4 sm:pb-4">Explore Dun Yan&apos;s mini AI/Data Science related projects that I built since I started to learn how to code <br />Enjoy ~ :)</p>

          <div className="pt-10 pb-20">
          <dl className="space-y-10 md:space-y-0 md:grid md:grid-cols-2 md:gap-x-12 md:gap-y-10">
          <div className="flex">
            <div className="flex-shrink-0">
              <div className="flex items-center justify-center h-12 w-12 rounded-md bg-yellow-600 text-white">
              <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" stroke-linejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z">
                </path>
              </svg>
              </div></div>
            <div className="ml-4">
            <dt className="text-lg leading-6 font-medium text-gray-900">
            <h3 className='text-lg leading-6 font-medium text-gray-100'>Visual recognitions</h3>
            </dt>
            <dd className="mt-2 text-base text-gray-500">Browse your most listened content on Spotify during last month, 6 months, or since you started using Spotify.</dd>
            </div>
          </div>
          <div className="flex">
            <div className="flex-shrink-0">
              <div className="flex items-center justify-center h-12 w-12 rounded-md bg-yellow-600 text-white bg-">
              <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" stroke-linejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z">
                </path>
              </svg>
              </div></div>
            <div className="ml-4">
            <dt className="text-lg leading-6 font-medium text-gray-900">
            <h3 className='text-lg leading-6 font-medium text-gray-100'>Voice speech</h3>
            </dt>
            <dd className="mt-2 text-base text-gray-500">Browse your most listened content on Spotify during last month, 6 months, or since you started using Spotify.</dd>
            </div>
          </div>
          <div className="flex">
            <div className="flex-shrink-0">
              <div className="flex items-center justify-center h-12 w-12 rounded-md bg-yellow-600 text-white bg-">
              <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z">
                </path>
              </svg>
              </div></div>
            <div className="ml-4">
            <dt className="text-lg leading-6 font-medium text-gray-900">
            <h3 className='text-lg leading-6 font-medium text-gray-100'>Custom time ranges</h3>
            </dt>
            <dd className="mt-2 text-base text-gray-500">Browse your most listened content on Spotify during last month, 6 months, or since you started using Spotify.</dd>
            </div>
          </div>
          <div className="flex">
            <div className="flex-shrink-0">
              <div className="flex items-center justify-center h-12 w-12 rounded-md bg-yellow-600 text-white bg-">
              <svg className="h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" stroke-linejoin="round" strokeWidth="2" d="M12 8v4l3 3m6-3a9 9 0 11-18 0 9 9 0 0118 0z">
                </path>
              </svg>
              </div></div>
            <div className="ml-4">
            <dt className="text-lg leading-6 font-medium text-gray-900">
            <h3 className='text-lg leading-6 font-medium text-gray-100'>Custom time ranges</h3>
            </dt>
            <dd className="mt-2 text-base text-gray-500">Browse your most listened content on Spotify during last month, 6 months, or since you started using Spotify.</dd>
            </div>
          </div>
          </dl>
          </div>      
        </main>
        <Footer />
      </div>
    </div>
  )
}